server:
  port: 8014

spring:
  application:
    name: ReviewService

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
        probability: 1 #100% (default = 10%)

  data:
    mongodb:
      port: 27017
      database: librarySystem_db
      host: localhost

  kafka:
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: kafka


  main:
    allow-circular-references: true
    web-application-type: reactive
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/




app:
  topic: reviewTopic