server:
  port: 8761

#  zipkin:
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1 #100% (default = 10%)
#
#eureka:
#  client:
#    registerWithEureka: false   #telling the server not to register himself in the service registry
#    fetchRegistry: false
    
    
